version: "3"
services:
  backend:
    build: ./backend
    ports: ["8080:8080"]

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nanourl

  redis:
    image: redis:latest
